version: "3"

networks:
  issues:
    driver: bridge

services:
  zookeeper:
    image: zookeeper:3.5
    networks:
      - issues
  kafka:
    image: wurstmeister/kafka:2.11-2.0.0
    depends_on:
      - zookeeper
    environment:
      - KAFKA_ADVERTISED_PORT=9092
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper
      - KAFKA_ADVERTISED_HOST_NAME=kafka
      - ZOOKEEPER_CONNECTION_TIMEOUT_MS=180000
      - KAFKA_CREATE_TOPICS=micronaut:1:1,spring:1:1
    networks:
      - issues
  consumer:
    image: consumer:0.1
    environment:
      - EUREKA_HOST=eureka
      - MICRONAUT_SERVER_HOST=consumer
    depends_on:
      - kafka
    networks:
      - issues
  producer:
    image: producer:0.1
    environment:
      - EUREKA_HOST=eureka
      - MICRONAUT_SERVER_HOST=producer
#      - JAVA_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005
    depends_on:
      - kafka
    ports:
      - "8080:8080"
#      - "5005:5005"
    networks:
      - issues
